// <auto-generated />
using System;
using AccidenteTransito.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccidenteTransito.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210918164313_Ini")]
    partial class Ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AccidenteTransito.App.Dominio.Accidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AgenteTransitoId")
                        .HasColumnType("int");

                    b.Property<string>("Barrio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvolucradoId")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<int>("TipoAccidente")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgenteTransitoId");

                    b.HasIndex("InvolucradoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Accidentes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Accidente");
                });

            modelBuilder.Entity("AccidenteTransito.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("AccidenteTransito.App.Dominio.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("AccidenteTransito.App.Dominio.Historia", b =>
                {
                    b.HasBaseType("AccidenteTransito.App.Dominio.Accidente");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdHistoria")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Historia");
                });

            modelBuilder.Entity("AccidenteTransito.App.Dominio.AgenteTransito", b =>
                {
                    b.HasBaseType("AccidenteTransito.App.Dominio.Persona");

                    b.Property<int>("NumeroPlaca")
                        .HasColumnType("int");

                    b.Property<string>("Rango")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AgenteTransito");
                });

            modelBuilder.Entity("AccidenteTransito.App.Dominio.Involucrado", b =>
                {
                    b.HasBaseType("AccidenteTransito.App.Dominio.Persona");

                    b.Property<int>("AgenteVial")
                        .HasColumnType("int");

                    b.Property<string>("Alcoholemia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionCasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaExpedicionDocumento")
                        .HasColumnType("datetime2");

                    b.Property<string>("PresentaLicencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Involucrado");
                });

            modelBuilder.Entity("AccidenteTransito.App.Dominio.Accidente", b =>
                {
                    b.HasOne("AccidenteTransito.App.Dominio.AgenteTransito", "AgenteTransito")
                        .WithMany()
                        .HasForeignKey("AgenteTransitoId");

                    b.HasOne("AccidenteTransito.App.Dominio.Involucrado", "Involucrado")
                        .WithMany()
                        .HasForeignKey("InvolucradoId");

                    b.HasOne("AccidenteTransito.App.Dominio.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("AgenteTransito");

                    b.Navigation("Involucrado");

                    b.Navigation("Vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
